In [6]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv('data.csv')

In [8]:
df = pd.get_dummies(df)
df.head

<bound method NDFrame.head of       Rooms  Type    Price  Method  Distance  Postcode  Bedroom2  Bathroom  \
0         2     1  1035000       2       2.5      3067         2         1
1         3     1  1465000       4       2.5      3067         3         2
2         4     1  1600000       5       2.5      3067         3         1
3         3     1  1876000       2       2.5      3067         4         2
4         2     1  1636000       2       2.5      3067         2         1
...     ...   ...      ...     ...       ...       ...       ...       ...
6825      2     1   650000       1      14.5      3087         2         1
6826      4     1   635000       2      14.7      3030         4         2
6827      3     1  1031000       4       6.8      3016         3         2
6828      4     1  2500000       1       6.8      3016         4         1
6829      4     1  1285000       4       6.3      3013         4         1

      Car  Landsize  BuildingArea  YearBuilt  CouncilArea  Lattitude  \
0       0       156          79.0       1900         30.0  -37.80790
1       0       134         150.0       1900         30.0  -37.80930
2       2       120         142.0       2014         30.0  -37.80720
3       0       245         210.0       1910         30.0  -37.80240
4       2       256         107.0       1890         30.0  -37.80600
...   ...       ...           ...        ...          ...        ...
6825    1       210          79.0       2006          NaN  -37.70657
6826    1       662         172.0       1980          NaN  -37.89327
6827    2       333         133.0       1995          NaN  -37.85927
6828    5       866         157.0       1920          NaN  -37.85908
6829    1       362         112.0       1920          NaN  -37.81188

      Longtitude  Regionname  Propertycount
0      144.99340           3           4019
1      144.99440           3           4019
2      144.99410           3           4019
3      144.99930           3           4019
4      144.99540           3           4019
...          ...         ...            ...
6825   145.07878           3           2329
6826   144.64789           7          16166
6827   144.87904           7           6380
6828   144.89299           7           6380
6829   144.88449           7           6543

[6830 rows x 17 columns]>

In [9]:
# Assuming df is your DataFrame
correlation_matrix = df.corr()

correlation_matrix

,Rooms,Type,Price,Method,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
Rooms,1.000000,-0.579983,0.517718,-0.048423,0.289763,0.068674,0.955851,0.613285,0.420493,0.099031,0.603150,-0.049272,-0.161131,0.009005,0.096665,-0.005093,-0.100447
Type,-0.579983,1.000000,-0.419183,0.088179,-0.240904,0.008063,-0.569295,-0.273788,-0.281780,-0.045246,-0.388990,0.320428,0.095130,-0.102741,0.002320,0.053642,0.098420
Price,0.517718,-0.419183,1.000000,-0.041462,-0.164975,0.109343,0.500452,0.492481,0.250916,0.073536,0.520492,-0.307343,-0.130870,-0.216919,0.209786,0.090802,-0.053336
Method,-0.048423,0.088179,-0.041462,1.000000,-0.058832,-0.031344,-0.044946,-0.006614,-0.014382,-0.015780,-0.040639,0.024371,0.028821,0.000390,-0.048818,0.025594,-0.020742
Distance,0.289763,-0.240904,-0.164975,-0.058832,1.000000,0.438274,0.296105,0.124044,0.265142,0.082449,0.155148,0.258462,-0.229657,-0.101092,0.215594,-0.094625,-0.061433
Postcode,0.068674,0.008063,0.109343,-0.031344,0.438274,1.000000,0.071611,0.112776,0.049226,0.039998,0.081791,0.036819,-0.052010,-0.374904,0.430579,-0.013522,0.058542
Bedroom2,0.955851,-0.569295,0.500452,-0.044946,0.296105,0.071611,1.000000,0.616832,0.424041,0.098066,0.588463,-0.038126,-0.158061,0.013882,0.095534,-0.013485,-0.098438
Bathroom,0.613285,-0.273788,0.492481,-0.006614,0.124044,0.112776,0.616832,1.000000,0.335331,0.081680,0.539717,0.166412,-0.093624,-0.066983,0.119573,0.036411,-0.062127
Car,0.420493,-0.281780,0.250916,-0.014382,0.265142,0.049226,0.424041,0.335331,1.000000,0.113427,0.331702,0.114340,-0.149610,0.003350,0.061410,0.005498,-0.033258
Landsize,0.099031,-0.045246,0.073536,-0.015780,0.082449,0.039998,0.098066,0.081680,0.113427,1.000000,0.082815,0.031474,-0.029790,0.013133,0.026882,-0.009509,-0.014909
BuildingArea,0.603150,-0.388990,0.520492,-0.040639,0.155148,0.081791,0.588463,0.539717,0.331702,0.082815,1.000000,0.017940,-0.162304,-0.042230,0.107153,0.031412,-0.063315
YearBuilt,-0.049272,0.320428,-0.307343,0.024371,0.258462,0.036819,-0.038126,0.166412,0.114340,0.031474,0.017940,1.000000,-0.053511,0.064333,-0.005064,-0.026114,0.005116
CouncilArea,-0.161131,0.095130,-0.130870,0.028821,-0.229657,-0.052010,-0.158061,-0.093624,-0.149610,-0.029790,-0.162304,-0.053511,1.000000,0.127177,-0.176712,-0.077807,0.011064
Lattitude,0.009005,-0.102741,-0.216919,0.000390,-0.101092,-0.374904,0.013882,-0.066983,0.003350,0.013133,-0.042230,0.064333,0.127177,1.000000,-0.362765,-0.310796,0.060940
Longtitude,0.096665,0.002320,0.209786,-0.048818,0.215594,0.430579,0.095534,0.119573,0.061410,0.026882,0.107153,-0.005064,-0.176712,-0.362765,1.000000,-0.469294,0.052395
Regionname,-0.005093,0.053642,0.090802,0.025594,-0.094625,-0.013522,-0.013485,0.036411,0.005498,-0.009509,0.031412,-0.026114,-0.077807,-0.310796,-0.469294,1.000000,-0.149624
Propertycount,-0.100447,0.098420,-0.053336,-0.020742,-0.061433,0.058542,-0.098438,-0.062127,-0.033258,-0.014909,-0.063315,0.005116,0.011064,0.060940,0.052395,-0.149624,1.000000

In [10]:
# Set the correlation threshold
threshold = 0.8

# Find and remove highly correlated features
correlated_features = set()
for i in range(len(correlation_matrix.columns)):
    for j in range(i):
        if abs(correlation_matrix.iloc[i, j]) > threshold:
            colname = correlation_matrix.columns[i]
            correlated_features.add(colname)

# Drop the highly correlated features
df = df.drop(columns=correlated_features)

In [11]:
df.head()

,Rooms,Type,Price,Method,Distance,Postcode,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,2,1,1035000,2,2.5,3067,1,0,156,79.0,1900,30.0,-37.8079,144.9934,3,4019
1,3,1,1465000,4,2.5,3067,2,0,134,150.0,1900,30.0,-37.8093,144.9944,3,4019
2,4,1,1600000,5,2.5,3067,1,2,120,142.0,2014,30.0,-37.8072,144.9941,3,4019
3,3,1,1876000,2,2.5,3067,2,0,245,210.0,1910,30.0,-37.8024,144.9993,3,4019
4,2,1,1636000,2,2.5,3067,1,2,256,107.0,1890,30.0,-37.8060,144.9954,3,4019

In [12]:
file_path = 'final_dataframe.csv'

# Save the DataFrame to a CSV file
df.to_csv(file_path, index=False)

print(f'DataFrame has been saved to {file_path}')

DataFrame has been saved to final_dataframe.csv

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6830 entries, 0 to 6829
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Rooms          6830 non-null   int64
 1   Type           6830 non-null   int64
 2   Price          6830 non-null   int64
 3   Method         6830 non-null   int64
 4   Distance       6830 non-null   float64
 5   Postcode       6830 non-null   int64
 6   Bathroom       6830 non-null   int64
 7   Car            6830 non-null   int64
 8   Landsize       6830 non-null   int64
 9   BuildingArea   6830 non-null   float64
 10  YearBuilt      6830 non-null   int64
 11  CouncilArea    6196 non-null   float64
 12  Lattitude      6830 non-null   float64
 13  Longtitude     6830 non-null   float64
 14  Regionname     6830 non-null   int64
 15  Propertycount  6830 non-null   int64
dtypes: float64(5), int64(11)
memory usage: 853.9 KB

In [14]:
import pandas as pd
import statsmodels.api as sm
from statsmodels.formula.api import ols


# Assuming 'Method' and 'Price' are columns in your DataFrame
formula = 'Price ~ C(Method)'
model = ols(formula, data=df).fit()

anova_table = sm.stats.anova_lm(model, typ=2)

print(anova_table)

                 sum_sq      df          F        PR(>F)
C(Method)  4.532047e+13     4.0  25.347842  7.116341e-21
Residual   3.050676e+15  6825.0        NaN           NaN